server:
 port: 8008
  
spring:
   application:
      name: CONFIG-SERVER
   cloud:
      config:
         server:
             git:
               uri: https://github.com/waliedAfro/cloud-config-server
               clone-on-start: true
      
               
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      
      server-url:
         defaultZone: http://localhost:8761/eureka/
 
instance:
   hostname: localhost